version: "app/v1"
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "default"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      PGUSER: "postgres"
      PGHOST: "postgres"
      PGDATABASE: "default"
      PGPASSWORD: "password"
      PGPORT: 5432
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: always
    ports:
      - "3000:80"
